### ISSUE TITLE
Cannot compile any overlay in Android 11 DP 2.1

### ISSUE THREAD

**Issue by djforesm** [KpChuck/K-Manager#14]
Build version: 43 
Build date: 1979-11-30 00:00:00 
Current date: 2020-04-21 13:19:46 
Device: Google Pixel 4 XL 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Error modding rom I think: 
org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1070)
org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1028)
kpchuck.kklock.utils.ApkBuilder.decompileSysUI(ApkBuilder.java:202)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:99)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:53)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:923)
java.io.IOException: Destination '/storage/emulated/0/K-Klock/inputFiles' directory cannot be created
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:155)
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:53)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

User actions: 
2020-04-21 13:17:57: MainActivity resumed

**Comment by KpChuck** [comment]
Think this might be the scoped storage thing android 11 brought in. I changed all the storage to use K-Managers app file directory so now it should work better
[K-Manager-debug.zip](https://github.com/KpChuck/K-Manager/files/4568370/K-Manager-debug.zip)

**Comment by ecompton59** [comment]
Thank you do you need report I'll send
