### ISSUE TITLE
Error when compiling for Substratum 

### ISSUE THREAD

**Issue by NetSpeedz** [KpChuck/K-Manager#17]
Trying to compile for substratum and get an error screen. Log file below.

Build version: 44 
Build date: 1979-11-30 00:00:00 
Current date: 2022-01-08 22:37:03 
Device: Google Pixel 5 Android 11
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Error modding rom I think: 
org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1070)
org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1028)
kpchuck.kklock.utils.ApkBuilder.decompileSysUI(ApkBuilder.java:199)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:96)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:52)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:923)
java.io.IOException: Destination '/storage/emulated/0/K-Klock/inputFiles' directory cannot be created
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:152)
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:52)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

User actions: 
2022-01-08 22:36:41: MainActivity resumed
2022-01-08 22:36:41: SplashActivity destroyed

**Comment by JooJooBee666** [comment]
Same here:
Build version: 44 
Build date: 1979-11-30 00:00:00 
Current date: 2022-11-29 08:57:53 
Device: Fx_tec_Pro1X QX1050 
`Build version: 44 
Build date: 1979-11-30 00:00:00 
Current date: 2022-11-29 08:57:53 
Device: Fx_tec_Pro1X QX1050 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Error modding rom I think: 
java.util.Objects.requireNonNull(Objects.java:220)
java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
java.util.Arrays.asList(Arrays.java:3725)
kpchuck.kklock.utils.ApkBuilder.decompileSysUI(ApkBuilder.java:187)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:96)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:52)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:923)
java.lang.NullPointerException
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:152)
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:52)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

User actions: 
2022-11-29 08:55:23: MainActivity resumed
2022-11-29 08:55:24: SplashActivity destroyed
`
