### ISSUE TITLE
I get this whenever i try and build the apk

### ISSUE THREAD

**Issue by itsfiras** [KpChuck/K-Manager#6]
Build version: 32 
Build date: 1979-11-30 00:00:00 
Current date: 2018-10-25 22:52:56 
Device: LGE LG-M703 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Error modding rom I think: 
org.apache.harmony.xml.dom.InnerNodeImpl.removeChild(InnerNodeImpl.java:181)
kpchuck.kklock.xml.XmlWork.fixForLg(XmlWork.java:634)
kpchuck.kklock.xml.XmlWork.setupStatusBar(XmlWork.java:423)
kpchuck.kklock.xml.XmlWork.modController(XmlWork.java:157)
kpchuck.kklock.xml.XmlWork.<init>(XmlWork.java:66)
kpchuck.kklock.utils.ApkBuilder.modTheRomZip(ApkBuilder.java:320)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:123)
kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:61)
android.os.AsyncTask$2.call(AsyncTask.java:333)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)
org.w3c.dom.DOMException
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:177)
	at kpchuck.kklock.utils.ApkBuilder.doInBackground(ApkBuilder.java:61)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

User actions: 
2018-10-25 22:51:41: MainActivity resumed
2018-10-25 22:51:59: MainActivity paused
2018-10-25 22:51:59: InformationWebViewActivity created
2018-10-25 22:51:59: InformationWebViewActivity resumed
2018-10-25 22:52:49: InformationWebViewActivity paused
2018-10-25 22:52:49: MainActivity destroyed
2018-10-25 22:52:49: MainActivity created
2018-10-25 22:52:49: MainActivity resumed
2018-10-25 22:52:50: InformationWebViewActivity destroyed

**Comment by KpChuck** [comment]
Can you upload the SystemUI.apk from the template? Thanks

**Comment by KpChuck** [comment]
Press Desktop version if you're on mobile. An option to upload will show up below the comment box.

**Comment by itsfiras** [comment]
[systemui.zip](https://github.com/KpChuck/K-Manager/files/2527325/systemui.zip)

**Comment by KpChuck** [comment]
Should be fixed by this https://github.com/KpChuck/K-Manager/commit/33f4dec9222b951d8b0db8b9962fd201af32fab6

At least it built the apk for me. I'll upload a beta apk on https://t.me/kklockbeta tomorrow so you can check if everything works.

**Comment by KpChuck** [comment]
Let me know if this works

[K-Manager-v32.1-beta.apk.zip](https://github.com/KpChuck/K-Manager/files/2597023/K-Manager-v32.1-beta.apk.zip)

**Comment by itsfiras** [comment]
It's working fine now
